name: Website build doc from tag
on:
  push:
    tags:
      - 'v*'
      - 'testv*'
    branches: [master, werfio2]
jobs:

  build:
    name: Converge
    runs-on: tfprod-werf
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set Helm release name
      id: value_set
      run: |
          echo "Version=$( echo $GITHUB_REF | cut -d\/ -f 3 | sed 's/\+/-plus-/' | sed 's/\_/-u-/')" >> $GITHUB_ENV

    - name: Deploy website to test
      uses: werf/actions/converge@master
      with:
        env: test
        group: 1.2
        channel: alpha
      env:
        WERF_RELEASE: "werfio-ng-${{ env.Version }}-test"
        WERF_DIR: "docs"
        WERF_LOG_VERBOSE: "on"
        WERF_KUBE_CONTEXT: dev
        WERF_SET_GITHUB_REF: "global.github_ref=${{ github.ref }}"

    - name: Deploy website to production
      uses: werf/actions/converge@master
      with:
        env: production
        group: 1.2
        channel: alpha
      env:
        WERF_RELEASE: "werfio-ng-${{ env.Version }}-production"
        WERF_DIR: "docs"
        WERF_LOG_VERBOSE: "on"
        WERF_KUBE_CONTEXT: prod
        WERF_SET_GITHUB_REF: "global.github_ref=${{ github.ref }}"
